import type { SanwoProviderDefinition } from "@sanwohq/types";
import { template } from "./template.js";

export const stripeProvider: SanwoProviderDefinition = {
  id: "stripe",
  name: "stripe",
  displayName: "Stripe",
  template,
  website: "https://stripe.com",
  documentation: "https://docs.stripe.com",
  amountInMinorUnit: true,
  supportedCurrencies: [
    "USD",
    "EUR",
    "GBP",
    "CAD",
    "AUD",
    "JPY",
    "CHF",
    "HKD",
    "SGD",
    "SEK",
    "DKK",
    "NOK",
    "NZD",
    "MXN",
    "BRL",
    "INR",
    "NGN",
    "ZAR",
    "KES",
    "GHS",
  ],
  supportedCountries: [
    "US",
    "GB",
    "CA",
    "AU",
    "DE",
    "FR",
    "JP",
    "SG",
    "HK",
    "NL",
    "IE",
    "SE",
    "DK",
    "NO",
    "NZ",
    "MX",
    "BR",
    "IN",
    "NG",
    "ZA",
    "KE",
    "GH",
  ],
  paymentMethods: [
    "card",
    "apple_pay",
    "google_pay",
    "bank_transfer",
    "sepa_debit",
    "ideal",
    "klarna",
    "afterpay",
    "cash_app",
    "link",
  ],
};
